baseURL = "https://monstrix.ru/"
languageCode = "ru"
title = "MONSTRIX"
theme = "terminal"
copyright = "© 2025 MONSTRIX | Лицензия <a href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\" target=\"_blank\">CC BY-NC-SA 4.0</a>"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  customCSS = ["css/monstrix-custom.css"]
  showMenuItems = 7
  logoHomeLink = "/"
  autoCover = true
  ReadMore = " Читать → "  # ← ДОБАВЬ ЭТУ СТРОКУ!


[menu]
  [[menu.main]]
    name = "Проекты"
    url = "/projects/"
    weight = 1
  [[menu.main]]
    name = "Прошивки"
    url = "/firmware/"
    weight = 2
  [[menu.main]]
    name = "Гайды"
    url = "/guides/"
    weight = 3
  [[menu.main]]
    name = "Компоненты"
    url = "/components/"
    weight = 4
  [[menu.main]]
    name = "Ссылки"
    url = "/links/"
    weight = 5
  [[menu.main]]
    name = "Поддержать"
    url = "/support/"
    weight = 6
  [[menu.main]]
    name = "О проекте"
    url = "/about/"
    weight = 7
