baseURL = "https://monstrix.ru"
languageCode = "ru"
title = "MONSTRIX"
theme = "terminal"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  customCSS = ["css/monstrix-custom.css"]
